In [18]:
import sys
from pathlib import Path
import pickle
import numpy as np
import matplotlib.pyplot as plt
import MDAnalysis as mda
import torch
import torch.nn as nn
import torch.nn.functional as F
from primitives import gaussian_blur, get_box_atm_indices, Residue
from scipy.ndimage import gaussian_filter
from scipy.signal.windows import gaussian
from matplotlib.pyplot import figure
# from pyuul import VolumeMaker # the main PyUUL module
from pyuul import utils
from myvolmaker import Voxels
from proteinshake.tasks import EnzymeClassTask, ProteinProteinInterfaceTask
from proteinshake.datasets import Dataset
from torch.utils.data import DataLoader
from pytorch3d.io import IO
from pytorch3d.ops import cubify

# Use proteins with Enzyme Class annotations
# Convert them to voxels with a voxelsize of 10 Angstrom
# Load into PyTorch data structures
# task = ProteinProteinInterfaceTask().to_voxel(voxelsize=10).torch()
# task = ProteinProteinInterfaceTask()
# task.to_voxel(voxelsize=10).torch()
# train, test = DataLoader(task.train), DataLoader(task.test)

casa = Path("/home/pbarletta/labo/23/paco")
dlp = Path("/home/pbarletta/labo/22/locuaz/rebin/dlpacker")
weights_path = Path(dlp, "DLPacker_weights.h5")
lib_path = Path(dlp, "library.npz")
charges_path = Path(dlp, "charges.rtp")

In [19]:
input_pdb_fn = Path(casa, "a.pdb")
coords, atname = utils.parsePDB(input_pdb_fn)
atoms_channel = utils.atomlistToChannels(atname)
radius = utils.atomlistToRadius(atname)
resolution = 1

volmaker = Voxels(device="cpu",sparse=False)
voxelized_volume = volmaker(coords, radius, atoms_channel,
                            resolution=resolution, cubes_around_atoms_dim=5,
                            function="gaussian")
voxels = voxelized_volume.sum(1)[:, None, :, :]
sp_voxels = voxels.to_sparse()
sp_voxels = sp_voxels[0, 0].coalesce()
volmaker.boxsize, volmaker.lato

((31, 21, 21), 11)

In [21]:
voxels.ndim

5

In [30]:
d = torch.cuda.device(0)

In [24]:
a = torch.rand((2, 3))

In [42]:
b = a.to(torch.float16).to('cuda')

In [93]:
t = torch.tensor([.09, .86, .1])
F.softmax(t, dim=0)

tensor([0.2398, 0.5180, 0.2422])

In [90]:
torch.softmax)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype, *, Tensor out)
 * (Tensor input, name dim, *, torch.dtype dtype)


In [54]:
nn.init.kaiming_normal_(b, mode='fan_out', nonlinearity='leaky_relu')

tensor([[ 0.8218,  1.3896,  1.1660],
        [-1.3145,  0.6304, -0.6138]], device='cuda:0', dtype=torch.float16)

In [55]:
nn.init._calculate_fan_in_and_fan_out(b)

(3, 2)

In [62]:
c = torch.rand((1, 1))

In [78]:
l = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=(3, 3))

In [79]:
nn.init._calculate_fan_in_and_fan_out(l.weight.data)

(9, 54)

In [89]:
a.unsqueeze(-1).shape

torch.Size([2, 3, 1])

In [68]:
nn.init.normal_(c, -3, 3)

tensor([[-0.5556]])

In [3]:
coords = volmaker.get_voxels_coordinates(atoms_channel)

In [4]:
def write_pdb_dots(voxel_coords, voxel_density, ndots: int, out_fn) :
    u = mda.Universe.empty(n_atoms = ndots, trajectory=True)
    u.add_TopologyAttr('name', ['H'] * ndots)
    u.add_TopologyAttr('type', ['H'] * ndots)
    u.add_TopologyAttr('tempfactor', np.array(voxel_density))
    u.atoms.positions = np.array(voxel_coords) 
    u.atoms.write(out_fn)

In [5]:
nvoxels = torch.tensor(coords.shape[:-1]).prod().item()
flat_coords = coords.view((nvoxels, 3))

write_pdb_dots(flat_coords,
               voxels.view(flat_coords.shape[0]), flat_coords.shape[0], "../cubo.pdb")

/home/pbarletta/mambaforge/envs/torch/lib/python3.10/site-packages/MDAnalysis/coordinates/PDB.py:775: UserWarning: Unit cell dimensions not found. CRYST1 record set to unitary values.
  warnings.warn("Unit cell dimensions not found. "
/home/pbarletta/mambaforge/envs/torch/lib/python3.10/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  warnings.warn("Found no information for attr: '{}'"
/home/pbarletta/mambaforge/envs/torch/lib/python3.10/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'resnames' Using default value of 'UNK'
  warnings.warn("Found no information for attr: '{}'"
/home/pbarletta/mambaforge/envs/torch/lib/python3.10/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  warnings.warn("Found no information for attr: '{}'"
/home/pbarletta/mambaforge/envs/torch/lib/python3

In [6]:
density = voxels[0].view(flat_coords.shape[0])
idx = torch.where(voxels.view(flat_coords.shape[0]))[0]
write_pdb_dots(flat_coords[idx],
               density[idx],
               idx.shape[0], "../non_zero_cubo.pdb")

In [51]:
voxels[0, 0, 1, 1, 2]

tensor(5.9605e-08)

In [48]:
voxels[b[0]].sum()

tensor(513278.3125)

In [14]:
voxelized_volume[0, 0].view(flat_coords.shape[0])[idx]

torch.Size([163643])

In [8]:
voxels.view(flat_coords.shape[0])[idx].shape

torch.Size([163643])

---------

### old stuff

In [ ]:
g = gaussian(3, std=.6)
g3d = g[None, :, None] @ g[:, None, None] @ g[None, None, :]
g3d /= np.sum(g3d)
g3d = torch.from_numpy(g3d[None, None, :, :].astype(np.float32))

xx = F.conv3d(voxels, g3d, padding=1)

In [ ]:
fig, ax = plt.subplots(1, 2)
l = 30
ax[0].imshow(voxels[0][0][l, :, :])
ax[1].imshow(xx[0][0][l, :, :])